version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: wallet-postgres
    restart: always
    env_file:
      - config.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet_user -d wallet_db"]
      interval: 2s
      timeout: 2s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-service
    env_file:
      - config.env
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy

  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: wallet-service-test
    env_file:
      - config.env
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres_data: