version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: wallet-postgres
    restart: always
    env_file:
      - config.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
volumes:
  postgres_data: